# Generated by Django 4.2.19 on 2025-03-05 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="SorumluEkip",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("isim", models.CharField(max_length=255)),
                ("unvan", models.CharField(max_length=100)),
                ("telefon", models.CharField(max_length=15)),
                ("eposta", models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name="Proje",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("baslik", models.CharField(max_length=255)),
                (
                    "tur",
                    models.CharField(
                        choices=[("internal", "Internal"), ("external", "External")],
                        max_length=10,
                    ),
                ),
                ("kurum", models.CharField(max_length=255)),
                ("telefon", models.CharField(max_length=15)),
                ("son_teslim_tarihi", models.DateField()),
                (
                    "sorumlu_ekip",
                    models.ManyToManyField(to="projectCreater.sorumluekip"),
                ),
            ],
        ),
    ]
