# Generated by Django 4.2.19 on 2025-03-05 18:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("projectCreater", "0001_initial"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Proje",
            new_name="projectCreater",
        ),
    ]
