# Generated by Django 4.2.19 on 2025-03-07 18:52

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("projectCreater", "0003_project_delete_projectcreater_delete_sorumluekip"),
    ]

    operations = [
        migrations.AlterField(
            model_name="project",
            name="internal_external",
            field=models.CharField(
                choices=[("internal", "Internal"), ("external", "External")],
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="project",
            name="sorumlu_ekip",
            field=models.ManyToManyField(
                related_name="ekip_uyeleri", to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AlterField(
            model_name="project",
            name="telefon",
            field=models.CharField(max_length=20),
        ),
    ]
