# Generated by Django 5.1.6 on 2025-03-08 19:23

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projectCreater', '0004_alter_project_internal_external_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='son_teslim_tarihi',
            new_name='last_delivery_date',
        ),
        migrations.RenameField(
            model_name='project',
            old_name='kurum',
            new_name='organisation',
        ),
        migrations.RenameField(
            model_name='project',
            old_name='telefon',
            new_name='phone',
        ),
        migrations.RenameField(
            model_name='project',
            old_name='sorumlu_ekip_uyesi',
            new_name='team_lead',
        ),
        migrations.RemoveField(
            model_name='project',
            name='sorumlu_ekip',
        ),
        migrations.AddField(
            model_name='project',
            name='team_members',
            field=models.ManyToManyField(related_name='team_members', to=settings.AUTH_USER_MODEL),
        ),
    ]
